export const games = [
  {
    id: 0,
    name: "Warzone Frontlines",
    description: `A fast-paced modern FPS focused on intense tactical combat and large-scale military operations. 
Take part in explosive battles across realistic environments, where teamwork, strategy and quick decisions determine victory. 
Customize your weapons, master different combat roles and experience dynamic firefights inspired by modern warfare.`,
    genres: ["action"],
    tags: ["fps", "multiplayer"],
    image: "images/frontlines.png",
    price: 204.99,
    discount: true,
    discountPercent: 27,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Steam",
    size: "125 GB",
    pegi: 16,
    releaseDate: "14 listopada 2026",
    background: "images/frontlines_bg.png",
    publisher: "IronPeak Interactive",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT"],
    priceOriginal: 280.81,
  },
  {
    id: 1,
    name: "Ashen Valor",
    description: `A dark fantasy RPG set in a broken world consumed by war, ancient magic and forgotten legends. 
Explore dangerous lands filled with mysterious ruins, powerful enemies and characters whose stories change depending on your choices. 
Build your own playstyle, discover hidden secrets and decide the fate of a kingdom struggling to survive.`,
    genres: ["rpg"],
    tags: ["fantasy", "open-world"],
    image: "images/ashenvalor.png",
    price: 149.99,
    discount: true,
    discountPercent: 40,
    platforms: ["PC"],
    activation: "Steam",
    size: "67 GB",
    pegi: 12,
    releaseDate: "25 czerwca 2026",
    background: "images/ashenvalor_bg.png",
    publisher: "Infinite Realm Entertainment",
    languages: ["PL", "EN", "DE", "FR"],
    priceOriginal: 249.99,
  },
  {
    id: 2,
    name: "Ultimate Soccer",
    description: `A realistic football simulation delivering fast matches, competitive gameplay and authentic stadium experiences. 
Create your dream team, master advanced tactics and compete against players from around the world. 
With improved physics, detailed animations and multiple game modes, every match feels unpredictable and exciting.`,
    genres: ["sports"],
    tags: ["football", "multiplayer"],
    image: "images/ultimate.png",
    price: 89.99,
    discount: true,
    discountPercent: 67,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "48 GB",
    pegi: 7,
    releaseDate: "12 grudnia 2025",
    background: "images/ultimate_bg.png",
    publisher: "Apex Interactive",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 272.7,
  },
  {
    id: 3,
    name: "Shadows of Revenir",
    description: `A dark stealth-action adventure where patience, planning and precision are the keys to survival. 
  Move through dangerous environments, avoid detection and use advanced techniques to overcome powerful enemies. 
  Discover the secrets behind a mysterious world filled with shadows, conspiracies and forgotten conflicts.`,
    genres: ["action"],
    tags: ["stealth", "fantasy"],
    image: "images/shadows.png",
    price: 24.99,
    discount: true,
    discountPercent: 90,
    platforms: ["PC", "PS5"],
    activation: "Ubisoft Connect",
    size: "33 GB",
    pegi: 16,
    releaseDate: "6 grudnia 2024",
    background: "images/shadows_bg.png",
    publisher: "ShadowWorks Studio",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 249.99,
  },
  {
    id: 4,
    name: "Infected - Requiem",
    description: `A survival horror experience set in a devastated world where humanity fights against a deadly infection. 
  Explore abandoned locations, manage limited resources and face terrifying creatures created by the outbreak. 
  Every decision matters as you uncover the truth behind the catastrophe and struggle to survive another day.`,
    genres: ["horror", "action"],
    tags: ["survival", "infected"],
    image: "images/infected.png",
    price: 275.38,
    discount: true,
    discountPercent: 35,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Steam",
    size: "92 GB",
    pegi: 18,
    releaseDate: "27 marca 2026",
    background: "images/infected_bg.png",
    publisher: "Crimson Pixel",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 423.66,
  },
  {
    id: 5,
    name: "Depths of Veridan",
    description: `A dark atmospheric sci-fi horror adventure set in the unexplored depths of an abandoned facility. 
  Investigate mysterious events, uncover lost research and face unknown threats hidden beneath the surface. 
  Combining exploration, survival mechanics and psychological horror, the game creates a tense experience where every corner hides a new danger.`,
    genres: ["action", "horror"],
    tags: ["sci-fi", "atmospheric"],
    image: "images/veridan.png",
    price: 213.04,
    discount: true,
    discountPercent: 77,
    platforms: ["PC", "Xbox Series X|S"],
    activation: "Microsoft Store",
    size: "82 GB",
    pegi: 16,
    releaseDate: "13 stycznia 2027",
    background: "images/veridan_bg.png",
    publisher: "Quantum Forge",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 926.26,
  },
  {
    id: 6,
    name: "Ruins of Avaris",
    description: `A cinematic action-adventure journey into ancient ruins filled with forgotten secrets, deadly traps and lost civilizations. 
  Explore mysterious locations, solve challenging puzzles and uncover the history of a world buried beneath time. 
  Fight dangerous enemies while discovering powerful artifacts that reveal the truth behind the legendary ruins of Avaris.`,
    genres: ["action"],
    tags: ["adventure", "exploration", "puzzle"],
    image: "images/ruins_avaris.png",
    price: 199.99,
    discount: true,
    discountPercent: 30,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Steam",
    size: "127 GB",
    pegi: 12,
    releaseDate: "5 lutego 2028",
    background: "images/ruins_avaris_bg.png",
    publisher: "Atlas Interactive",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 285.7,
  },
  {
    id: 7,
    name: "Nightfall Protocol",
    description: `A dark action game about a masked vigilante fighting corruption in a dangerous futuristic metropolis. 
  Use stealth, advanced combat techniques and detective skills to uncover criminal organizations controlling the city. 
  Explore a world full of secrets, moral choices and intense battles against enemies hiding in the shadows.`,
    genres: ["action"],
    tags: ["stealth", "combat", "superhero"],
    image: "images/nightfall_protocol.png",
    price: 179.99,
    discount: true,
    discountPercent: 25,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "152 GB",
    pegi: 16,
    releaseDate: "11 stycznia 2028",
    background: "images/nightfall_protocol_bg.png",
    publisher: "Black Falcon Entertainment",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 239.99,
  },
  {
    id: 8,
    name: "Gunsmoke Legends",
    description: `A western shooter set in a lawless frontier where survival depends on skill, courage and quick decisions. 
    Explore dusty towns, face dangerous outlaws and take part in intense duels across a forgotten era of the Wild West. 
    Build your reputation, uncover hidden stories and experience a world filled with crime, revenge and legendary gunslingers.`,
    genres: ["action"],
    tags: ["western", "shooter", "story"],
    image: "images/gunsmoke_legends.png",
    price: 149.99,
    discount: false,
    discountPercent: 0,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Rockstar Social Club",
    size: "98 GB",
    pegi: 18,
    releaseDate: "22 czerwca 2023",
    background: "images/gunsmoke_legends_bg.png",
    publisher: "WildRiver Games",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT"],
    priceOriginal: 149.99,
  },
  {
    id: 9,
    name: "Iron Frontline",
    description: `A tactical real-time strategy game where every decision can change the outcome of a brutal battlefield. 
    Command specialized units, manage resources and develop strategies to defeat enemy forces across massive war zones. 
    Experience intense military operations where planning, positioning and teamwork are essential for victory.`,
    genres: ["strategy"],
    tags: ["war", "tactics", "real-time"],
    image: "images/iron_frontline.png",
    price: 129.99,
    discount: true,
    discountPercent: 40,
    platforms: ["PC"],
    activation: "GOG",
    size: "27 GB",
    pegi: 12,
    releaseDate: "8 maja 2020",
    background: "images/iron_frontline_bg.png",
    publisher: "Steel Horizon Games",
    languages: ["PL", "EN"],
    priceOriginal: 216.65,
  },
  {
    id: 10,
    name: "Kingdoms of Dawn",
    description: `A historical strategy experience where you build powerful civilizations and guide your people through centuries of change. 
    Expand your kingdom, manage economy, develop technologies and make difficult decisions that shape the future of your empire. 
    Create alliances, wage wars and leave your mark on history through your leadership.`,
    genres: ["strategy"],
    tags: ["building", "civilization", "medieval"],
    image: "images/kingdoms_dawn.png",
    price: 99.99,
    discount: false,
    discountPercent: 0,
    platforms: ["PC"],
    activation: "GOG",
    size: "39 GB",
    pegi: 12,
    releaseDate: "28 sierpnia 2022",
    background: "images/kingdoms_dawn_bg.png",
    publisher: "Atlas Interactive",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 99.99,
  },
  {
    id: 11,
    name: "Nano Warzone",
    description: `A futuristic FPS where advanced technology and experimental nano-suits redefine modern combat. 
    Fight across a collapsing Earth filled with massive battles, high-tech weapons and powerful enemies. 
    Customize your abilities, adapt to different situations and experience fast-paced warfare in a world on the edge of destruction.`,
    genres: ["action"],
    tags: ["fps", "sci-fi", "futuristic"],
    image: "images/nano_warzone.png",
    price: 219.99,
    discount: true,
    discountPercent: 35,
    trending: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "127 GB",
    pegi: 16,
    releaseDate: "8 maja 2027",
    background: "images/nano_warzone_bg.png",
    publisher: "Neon Forge",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 338.45,
  },
  {
    id: 12,
    name: "Hollow Eclipse",
    description: `A terrifying survival horror adventure taking place aboard a forgotten space station drifting through the darkness of space. 
    Investigate abandoned areas, discover the secrets behind a mysterious incident and survive encounters with unknown creatures. 
    Manage limited resources and uncover a disturbing story hidden among the remains of the lost station.`,
    genres: ["horror"],
    tags: ["sci-fi", "survival", "space"],
    image: "images/hollow_eclipse.png",
    price: 189.99,
    discount: true,
    discountPercent: 50,
    trending: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "GOG",
    size: "77 GB",
    pegi: 18,
    releaseDate: "8 maja 2024",
    background: "images/hollow_eclipse_bg.png",
    publisher: "Quantum Forge",
    languages: ["PL", "EN"],
    priceOriginal: 379.98,
  },
  {
    id: 13,
    name: "Arcane Academy",
    description: `An open-world fantasy RPG where you discover the secrets of a forgotten magical academy. 
    Learn powerful spells, explore mysterious locations and uncover ancient knowledge hidden for generations. 
    Create your own magical path, interact with unique characters and decide how your abilities will shape the future of the wizarding world.`,
    genres: ["rpg"],
    tags: ["magic", "fantasy", "open-world"],
    image: "images/arcane_academy.png",
    price: 249.99,
    discount: true,
    discountPercent: 20,
    platforms: ["PC"],
    activation: "Ubisoft Connect",
    size: "57 GB",
    pegi: 12,
    releaseDate: "4 kwietnia 2027",
    background: "images/arcane_academy_bg.png",
    publisher: "Aurora Interactive",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 312.49,
  },
  {
    id: 14,
    name: "Outlaw’s Requiem",
    description: `An emotional western adventure about survival, loyalty and the difficult choices made on the frontier. 
    Follow the story of a person trying to find their place in a dangerous world ruled by criminals and lawless territories. 
    Explore open landscapes, meet unforgettable characters and experience a cinematic journey filled with action and personal conflicts.`,
    genres: ["action"],
    tags: ["western", "open-world", "story"],
    image: "images/outlaws_requiem.png",
    price: 279.99,
    discount: false,
    discountPercent: 0,
    platforms: ["PC"],
    activation: "GOG",
    size: "97 GB",
    pegi: 16,
    releaseDate: "8 maja 2021",
    background: "images/outlaws_requiem_bg.png",
    publisher: "WildRiver Games",
    languages: ["PL", "EN"],
    priceOriginal: 279.99,
  },
  {
    id: 15,
    name: "Crash Circuit X",
    description: `A chaotic arcade racing game focused on destruction, speed and spectacular crashes. 
    Compete in dangerous races where aggressive driving and risky moves are the key to victory. 
    Customize powerful vehicles, destroy your opponents and experience fast-paced events full of explosions and unpredictable moments.`,
    genres: ["racing"],
    tags: ["arcade", "destruction", "cars"],
    image: "images/crash_circuit_x.png",
    price: 89.99,
    discount: true,
    discountPercent: 60,
    trending: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Steam",
    size: "27 GB",
    pegi: 12,
    releaseDate: "28 maja 2017",
    background: "images/crash_circuit_x_bg.png",
    publisher: "Fireline Entertainment",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 224.98,
  },
  {
    id: 16,
    name: "Neon Vice Syndicate",
    description: `An open-world crime adventure set in a neon-lit metropolis filled with corruption, ambition and endless opportunities. 
    Build your reputation in a city controlled by powerful organizations, dangerous criminals and underground networks. 
    Explore a living world, complete high-risk missions, make important choices and create your own path through a world of chaos and freedom.`,
    genres: ["action"],
    tags: ["open-world", "crime", "sandbox"],
    image: "images/neon_vice_syndicate.png",
    price: 299.99,
    discount: false,
    discountPercent: 0,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "109 GB",
    pegi: 16,
    releaseDate: "29 listopada 2027",
    background: "images/neon_vice_syndicate_bg.png",
    publisher: "Neon Forge",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT", "PT-BR"],
    priceOriginal: 299.99,
  },
  {
    id: 17,
    name: "Midnight Drift Union",
    description: `A high-speed street racing experience where underground drivers compete for reputation and dominance after dark. 
    Master challenging drift techniques, customize your cars and escape from intense police pursuits across neon city streets. 
    Experience fast races, dangerous rivalries and a world where every corner can decide victory or defeat.`,
    genres: ["racing"],
    tags: ["street-racing", "drift", "cars"],
    image: "images/midnight_drift_union.png",
    price: 119.99,
    discount: true,
    discountPercent: 45,
    trending: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Rockstar Social Club",
    size: "98 GB",
    pegi: 16,
    releaseDate: "21 listopada 2025",
    background: "images/midnight_drift_union_bg.png",
    publisher: "Fireline Entertainment",
    languages: ["PL", "EN"],
    priceOriginal: 218.16,
  },
  {
    id: 18,
    name: "Silent Marksman",
    description: `A tactical sniper experience focused on precision, stealth and careful planning. 
    Take on challenging missions where every shot matters and patience is the key to survival. 
    Use advanced equipment, analyze enemy positions and complete operations from a distance without being detected.`,
    genres: ["action"],
    tags: ["sniper", "stealth", "war"],
    image: "images/silent_marksman.png",
    price: 159.99,
    discount: true,
    discountPercent: 30,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Steam",
    size: "59 GB",
    pegi: 12,
    releaseDate: "2 listopada 2025",
    publisher: "Black Falcon Entertainment",
    languages: ["PL", "EN", "DE", "FR"],
    priceOriginal: 228.56,
  },
  {
    id: 19,
    name: "Velocity Grand Prix 26",
    description: `A realistic Formula racing simulator delivering intense competition, advanced physics and authentic motorsport experiences. 
  Compete on legendary tracks, manage your career and adapt to changing weather conditions during every race. 
  Customize your vehicle, improve your driving skills and fight for championship glory against the fastest drivers in the world.`,
    genres: ["sports", "racing"],
    tags: ["f1", "simulation", "multiplayer"],
    image: "images/velocitygp26.png",
    price: 174.99,
    discount: true,
    discountPercent: 30,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "120 GB",
    pegi: 16,
    releaseDate: "12 grudnia 2025",
    publisher: "Apex Interactive",
    languages: ["PL", "EN", "DE"],
    priceOriginal: 249.99,
  },
  {
    id: 20,
    name: "Court Kings 26",
    description: `A next-generation basketball experience combining realistic gameplay, competitive matches and a deep career mode. 
  Create your own player, compete on street courts and professional arenas while developing your skills. 
  Join online leagues, challenge other players and become a legend of the basketball world.`,
    genres: ["sports"],
    tags: ["basketball", "nba", "multiplayer"],
    image: "images/courtkings26.png",
    price: 179.99,
    discount: true,
    discountPercent: 22,
    trending: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "122 GB",
    pegi: 7,
    releaseDate: "20 listopada 2026",
    publisher: "Apex Interactive",
    languages: ["PL", "EN", "DE", "FR", "ES", "IT"],
    priceOriginal: 229.99,
  },
  {
    id: 21,
    name: "Neon Rift: Eclipse Protocol",
    description: `A dark sci-fi RPG set in a neon-drenched megacity where corporations, factions and advanced technology control the future of humanity.  
  Play as a cyber-enhanced mercenary, upgrade your abilities with powerful implants and make decisions that influence the world around you.  
  Explore a massive futuristic city, uncover hidden conspiracies and shape your own story through choices with lasting consequences.`,
    genres: ["rpg"],
    tags: ["cyberpunk", "open-world", "sci-fi"],
    image: "images/neonrift.png",
    price: 174.99,
    discount: true,
    discountPercent: 35,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "Steam",
    size: "167 GB",
    pegi: 18,
    releaseDate: "7 lipca 2028",
    background: "images/neonrift_bg.png",
    publisher: "Neon Forge",
    languages: ["PL", "EN", "DE", "FR", "JA"],
    priceOriginal: 269.99,
  },
  {
    id: 22,
    name: "Starlight Odyssey: Genesis War",
    description: `A massive space opera RPG where you command a starship crew and explore the unknown corners of the galaxy.  
  Discover alien civilizations, form alliances and face conflicts that can change the future of entire worlds.  
  Customize your ship, manage your crew and make difficult decisions that determine the fate of countless civilizations.`,
    genres: ["rpg"],
    tags: ["sci-fi", "space", "story-driven"],
    image: "images/starlightodyssey.png",
    price: 164.99,
    discount: true,
    discountPercent: 28,
    trending: true,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "49 GB",
    pegi: 12,
    releaseDate: "2 marca 2027",
    publisher: "Infinite Realm Entertainment",
    languages: ["PL", "EN", "DE", "FR", "JA"],
    priceOriginal: 229.99,
  },
  {
    id: 23,
    name: "Frozen Dominion: Last Ember",
    description: `A brutal survival strategy game where humanity fights to survive on a frozen and unforgiving planet. 
    Build the last remaining city, manage limited resources and make difficult choices that decide the future of your people. 
    Balance survival, technology and social conflicts while trying to protect civilization from complete extinction.`,
    genres: ["strategy"],
    tags: ["survival", "city-builder", "post-apocalyptic"],
    image: "images/frozendomion.png",
    price: 279.99,
    discount: true,
    discountPercent: 30,
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    activation: "EA App",
    size: "121 GB",
    pegi: 18,
    releaseDate: "9 listopada 2027",
    publisher: "Steel Horizon Games",
    languages: ["PL", "EN", "DE", "FR"],
    priceOriginal: 399.99,
  },
];
