export const games = [
  {
    id: 0,
    name: "Warzone Frontlines",
    description: `A fast-paced modern FPS with intense tactical combat.`,
    genres: ["action"],
    tags: ["fps", "multiplayer"],
    image: "images/frontlines.png",
    price: 272.6,
    discount: true,
    discountPercent: 27,
  },
  {
    id: 1,
    name: "Ashen Valor",
    description: `A dark fantasy RPG where choices shape the fate of a broken world.`,
    genres: ["rpg"],
    tags: ["fantasy", "open-world"],
    image: "images/ashenvalor.png",
    price: 373.33,
    discount: true,
    discountPercent: 40,
  },
  {
    id: 2,
    name: "Ultimate Soccer",
    description: `A fast and realistic football simulation experience.`,
    genres: ["sports"],
    tags: ["football", "multiplayer"],
    image: "images/ultimate.png",
    price: 263.64,
    discount: true,
    discountPercent: 67,
  },
  {
    id: 3,
    name: "Shadows of Revenir",
    description: `A dark stealth-action game where silence and strategy decide your survival.`,
    genres: ["action"],
    tags: ["stealth", "fantasy"],
    image: "images/shadows.png",
    price: 240,
    discount: true,
    discountPercent: 90,
  },
  {
    id: 4,
    name: "Infected - Requiem",
    description: `A survival horror set in a world overrun by infection and chaos.`,
    genres: ["horror", "action"],
    tags: ["survival", "infected"],
    image: "images/infected.png",
    price: 275.38,
    discount: true,
    discountPercent: 35,
  },
  {
    id: 5,
    name: "Depths of Veridan",
    description: ``,
    genres: ["action", "horror"],
    tags: ["sci-fi", "atmospheric"],
    image: "images/veridan.png",
    price: 213.04,
    discount: true,
    discountPercent: 77,
  },
  {
    id: 6,
    name: "Ruins of Avaris",
    description:
      "A cinematic action-adventure exploring ancient ruins filled with traps and forgotten secrets.",
    genres: ["action"],
    tags: ["adventure", "exploration", "puzzle"],
    image: "images/ruins_avaris.png",
    price: 199.99,
    discount: true,
    discountPercent: 30,
  },
  {
    id: 7,
    name: "Nightfall Protocol",
    description:
      "A dark action game where a masked vigilante fights crime in a corrupted metropolis.",
    genres: ["action"],
    tags: ["stealth", "combat", "superhero"],
    image: "images/nightfall_protocol.png",
    price: 179.99,
    discount: true,
    discountPercent: 25,
  },
  {
    id: 8,
    name: "Gunsmoke Legends",
    description:
      "A western shooter set in lawless frontier towns filled with duels and outlaw gangs.",
    genres: ["action"],
    tags: ["western", "shooter", "story"],
    image: "images/gunsmoke_legends.png",
    price: 149.99,
    discount: false,
    discountPercent: 0,
  },
  {
    id: 9,
    name: "Iron Frontline",
    description:
      "A tactical RTS where you command squads in brutal large-scale battlefield operations.",
    genres: ["strategy"],
    tags: ["war", "tactics", "real-time"],
    image: "images/iron_frontline.png",
    price: 129.99,
    discount: true,
    discountPercent: 40,
  },
  {
    id: 10,
    name: "Kingdoms of Dawn",
    description:
      "A historical strategy game where you build empires and lead civilizations to glory.",
    genres: ["strategy"],
    tags: ["building", "civilization", "medieval"],
    image: "images/kingdoms_dawn.png",
    price: 99.99,
    discount: false,
    discountPercent: 0,
  },
  {
    id: 11,
    name: "Nano Warzone",
    description:
      "A futuristic FPS where advanced nano-suits redefine combat on a collapsing Earth.",
    genres: ["action"],
    tags: ["fps", "sci-fi", "futuristic"],
    image: "images/nano_warzone.png",
    price: 219.99,
    discount: true,
    discountPercent: 35,
  },
  {
    id: 12,
    name: "Hollow Eclipse",
    description:
      "A survival horror set aboard a drifting space station infested with unknown horrors.",
    genres: ["horror"],
    tags: ["sci-fi", "survival", "space"],
    image: "images/hollow_eclipse.png",
    price: 189.99,
    discount: true,
    discountPercent: 50,
  },
  {
    id: 13,
    name: "Arcane Academy",
    description:
      "An open-world magic RPG where you uncover secrets of a forgotten magical academy.",
    genres: ["rpg"],
    tags: ["magic", "fantasy", "open-world"],
    image: "images/arcane_academy.png",
    price: 249.99,
    discount: true,
    discountPercent: 20,
  },
  {
    id: 14,
    name: "Outlaw’s Requiem",
    description:
      "An emotional western adventure about survival, loyalty, and life on the frontier.",
    genres: ["action"],
    tags: ["western", "open-world", "story"],
    image: "images/outlaws_requiem.png",
    price: 279.99,
    discount: false,
    discountPercent: 0,
  },
  {
    id: 15,
    name: "Crash Circuit X",
    description:
      "A destructive racing game focused on chaos, crashes, and high-speed collisions.",
    genres: ["racing"],
    tags: ["arcade", "destruction", "cars"],
    image: "images/crash_circuit_x.png",
    price: 89.99,
    discount: true,
    discountPercent: 60,
  },
  {
    id: 16,
    name: "Neon Vice Syndicate",
    description:
      "An open-world crime saga set in a neon-lit city full of freedom and chaos.",
    genres: ["action"],
    tags: ["open-world", "crime", "sandbox"],
    image: "images/neon_vice_syndicate.png",
    price: 299.99,
    discount: false,
    discountPercent: 0,
  },
  {
    id: 17,
    name: "Midnight Drift Union",
    description:
      "Street racing under neon lights with intense police chases and drift battles.",
    genres: ["racing"],
    tags: ["street-racing", "drift", "cars"],
    image: "images/midnight_drift_union.png",
    price: 119.99,
    discount: true,
    discountPercent: 45,
  },
  {
    id: 18,
    name: "Silent Marksman",
    description:
      "A tactical sniper shooter focused on precision, stealth, and long-range eliminations.",
    genres: ["action"],
    tags: ["sniper", "stealth", "war"],
    image: "images/silent_marksman.png",
    price: 159.99,
    discount: true,
    discountPercent: 30,
  },
  {
    id: 19,
    name: "Velocity Grand Prix 26",
    description: `A high-speed Formula racing simulator with dynamic weather, career mode and realistic car physics.`,
    genres: ["sports", "racing"],
    tags: ["f1", "simulation", "multiplayer"],
    image: "images/velocitygp26.png",
    price: 319.99,
    discount: true,
    discountPercent: 30,
  },
  {
    id: 20,
    name: "Court Kings 26",
    description: `A next-gen basketball experience featuring street matches, career mode and online leagues.`,
    genres: ["sports"],
    tags: ["basketball", "nba", "multiplayer"],
    image: "images/courtkings26.png",
    price: 299.99,
    discount: true,
    discountPercent: 22,
  },
  {
    id: 21,
    name: "Neon Rift: Eclipse Protocol",
    description: `A dark sci-fi RPG set in a neon-drenched мегacity where choices shape factions, cyber implants and the fate of humanity.`,
    genres: ["rpg"],
    tags: ["cyberpunk", "open-world", "sci-fi"],
    image: "images/neonrift.png",
    price: 349.99,
    discount: true,
    discountPercent: 35,
  },
  {
    id: 22,
    name: "Starlight Odyssey: Genesis War",
    description: `A space opera RPG where you command a starship crew, explore alien worlds and decide the fate of entire civilizations.`,
    genres: ["rpg"],
    tags: ["sci-fi", "space", "story-driven"],
    image: "images/starlightodyssey.png",
    price: 329.99,
    discount: true,
    discountPercent: 28,
  },
  {
    id: 23,
    name: "Frozen Dominion: Last Ember",
    description: `A brutal survival strategy game where you build the last city on a frozen planet, manage scarce resources and make morally difficult decisions.`,
    genres: ["strategy"],
    tags: ["survival", "city-builder", "post-apocalyptic"],
    image: "images/frozendomion.png",
    price: 279.99,
    discount: true,
    discountPercent: 30,
  },
];
